@startuml
QWidget <|-- DoubleFolderPanel
QWidget <|-- FolderForm
QTableView <|-- FolderView
QSortFilterProxyModel <|-- FolderModel

DoubleFolderPanel *-- FolderForm
FolderForm *-- FolderModel
FolderForm *-- FolderView
FolderView o-- FolderModel
FolderModel *-- QItemSelectionModel
FolderView --- QItemSelectionModel

class FolderView{
    void keyPressEvent(QKeyEvent *)
}
note bottom: key,Mouse入力といったUIに関する処理を行う

@enduml

